services:
  console:
    build:
      context: ./rustfs-console
    container_name: rustfs-console
    ports:
      - "8080:80"
    restart: always

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    ports:
      - "9000:9000"
    environment:
      - RUSTFS_CONSOLE_ENABLE=false
      - RUSTFS_CORS_ALLOWED_ORIGINS=http://localhost:8080
    volumes:
      - ./data:/data
    command: server /data
    restart: always
